apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
spec:
  selector:
    matchLabels:
      app-of: error-04
  replicas: 3
  template:
    metadata:
      labels:
        app-of: error-04
    spec:
      containers:
        - image: gcr.io/kuar-demo/kuard-amd64:blue
          name: kuard
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          volumeMount:
            - name: test
              mountPath: /config
      volumes:
        - name: test
          configMap:
            name: test-cm