apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
spec:
  selector:
    matchLabels:
      app-of: error-05
  replicas: 2
  template:
    metadata:
      labels:
        app-of: error-05
    spec:
      containers:
        - image: gcr.io/kuar-demo/kuard-amd64:blue
          name: kuard
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 1Mi
            limits:
              cpu: 100m
              memory: 1Mi
