apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: error-01
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:kiowy-org/k8s-ckad-lab.git
    targetRevision: HEAD
    path: .to_fix/error-01

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

  destination:
    namespace: error-01
    server: https://kubernetes.default.svc
---