apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
spec:
  selector:
    matchLabels:
      app-of: error-01
  replicas: 2
  template:
    metadata:
      labels:
        app-of: error-01
    spec:
      containers:
        - image: gcr.io/kuar-demo/kuaed-amd64:blue
          name: kuard
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP